#!/usr/bin/env bash
#
# collect-diagnostics.sh — Dell Latitude 7420 / Linux Mint hardware & storage audit
#
# STRICTLY READ-ONLY. This script never writes to any block device, never mounts
# anything read-write, and never modifies system configuration.
#
# Serial numbers, the Dell service tag, MAC addresses and UUIDs are REDACTED by
# default so output is safe to commit to a public repository.
#
# Usage:
#   sudo ./scripts/collect-diagnostics.sh                 # redacted (default)
#   sudo ./scripts/collect-diagnostics.sh --no-redact     # full, DO NOT COMMIT
#   sudo ./scripts/collect-diagnostics.sh -o /path/out.md
#
set -uo pipefail

REDACT=1
OUTFILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-redact) REDACT=0; shift ;;
    -o|--output) OUTFILE="${2:-}"; shift 2 ;;
    -h|--help)
      sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  echo "This script needs root for SMART, DMI and partition data. Re-run with sudo." >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAMP="$(date +%Y%m%d-%H%M%S)"
[[ -z "$OUTFILE" ]] && OUTFILE="${REPO_ROOT}/diagnostics/report-${STAMP}.md"
mkdir -p "$(dirname "$OUTFILE")"

# --- helpers ---------------------------------------------------------------

# Redact serials, service tags, MACs and UUIDs from stdin.
redact() {
  if [[ $REDACT -eq 1 ]]; then
    sed -E \
      -e 's/([Ss]erial [Nn]umber:[[:space:]]*)[A-Za-z0-9_-]+/\1[REDACTED]/g' \
      -e 's/(^|[[:space:]])(sn|SN)([[:space:]]*:[[:space:]]*)[A-Za-z0-9_-]+/\1\2\3[REDACTED]/g' \
      -e 's/([Ss]erial:[[:space:]]*)[A-Za-z0-9_-]+/\1[REDACTED]/g' \
      -e 's/\b([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}\b/[MAC-REDACTED]/g' \
      -e 's/\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b/[UUID-REDACTED]/g'
  else
    cat
  fi
}

# section "Title" command...
section() {
  local title="$1"; shift
  {
    echo
    echo "## ${title}"
    echo
    echo '```'
    if "$@" 2>&1; then :; else echo "(command unavailable or returned an error)"; fi
    echo '```'
  } | redact >> "$OUTFILE"
  echo "  · ${title}" >&2
}

# For pipelines / shell builtins
section_sh() {
  local title="$1"; shift
  {
    echo
    echo "## ${title}"
    echo
    echo '```'
    bash -c "$*" 2>&1 || echo "(command unavailable or returned an error)"
    echo '```'
  } | redact >> "$OUTFILE"
  echo "  · ${title}" >&2
}

# --- header ----------------------------------------------------------------

cat > "$OUTFILE" <<EOF
# Diagnostic Report

- **Generated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')
- **Host:** $(hostname)
- **Kernel:** $(uname -r)
- **Distribution:** $(. /etc/os-release && echo "$PRETTY_NAME")
- **Redaction:** $([[ $REDACT -eq 1 ]] && echo 'ENABLED (safe to commit)' || echo '*** DISABLED — DO NOT COMMIT ***')

> Generated by \`scripts/collect-diagnostics.sh\`. Read-only: no block device was
> written, no filesystem was mounted read-write, no configuration was changed.
EOF

echo "Collecting diagnostics -> $OUTFILE" >&2

# --- system identity -------------------------------------------------------

section_sh "System identity (DMI)" \
  'for f in sys_vendor product_name product_version bios_version bios_date board_name chassis_type; do
     printf "%-16s %s\n" "$f:" "$(cat /sys/class/dmi/id/$f 2>/dev/null)"
   done
   printf "%-16s %s\n" "product_serial:" "[REDACTED]"'

section_sh "Firmware mode" \
  '[ -d /sys/firmware/efi ] && echo "UEFI" || echo "Legacy BIOS / CSM"'

section "Secure Boot state" mokutil --sb-state
section "EFI boot entries" efibootmgr -v
section_sh "TPM" 'ls -l /dev/tpm* 2>/dev/null; echo "TPM major version: $(cat /sys/class/tpm/tpm0/tpm_version_major 2>/dev/null)"'

# --- cpu / memory ----------------------------------------------------------

section "CPU" lscpu
section_sh "CPU vulnerabilities" 'grep -r . /sys/devices/system/cpu/vulnerabilities/ 2>/dev/null | sed "s|.*/vulnerabilities/||"'
section_sh "CPU frequency policy" \
  'echo "scaling_driver:   $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver 2>/dev/null)"
   echo "scaling_governor: $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 2>/dev/null)"
   echo "intel_pstate:     $(cat /sys/devices/system/cpu/intel_pstate/status 2>/dev/null)"
   echo "energy_perf_pref: $(cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference 2>/dev/null)"'

section "Memory" free -h
section "Swap" swapon --show

# --- storage ---------------------------------------------------------------

section "Block devices" lsblk -o NAME,SIZE,TYPE,FSTYPE,LABEL,MOUNTPOINT,MODEL,TRAN,ROTA
section "Partition table (parted)" parted /dev/nvme0n1 unit s print free
section "Partition table (sgdisk)" sgdisk -p /dev/nvme0n1
section "Filesystem identifiers (blkid)" blkid
section "Mounted filesystems" findmnt -A
section "Disk usage" df -hT
section "TRIM / discard support" lsblk --discard
section_sh "I/O scheduler" 'for d in /sys/block/nvme*/queue/scheduler; do echo "$d: $(cat $d)"; done'

section "NVMe devices" nvme list
section "NVMe SMART / health" smartctl -a /dev/nvme0n1
section_sh "NVMe LBA formats" 'nvme id-ns /dev/nvme0n1 -H 2>/dev/null | grep -i "lbaf\|in use"'
section_sh "NVMe error log (last 10)" 'nvme error-log /dev/nvme0n1 2>/dev/null | head -40'

# --- power / thermal -------------------------------------------------------

section_sh "Battery health" \
  'BAT=$(upower -e 2>/dev/null | grep -i BAT | head -1)
   [ -n "$BAT" ] && upower -i "$BAT"
   echo "--- sysfs ---"
   for f in manufacturer model_name cycle_count energy_full_design energy_full capacity status; do
     printf "%-22s %s\n" "$f:" "$(cat /sys/class/power_supply/BAT0/$f 2>/dev/null)"
   done
   echo "--- charge thresholds ---"
   for f in charge_control_start_threshold charge_control_end_threshold; do
     printf "%-32s %s\n" "$f:" "$(cat /sys/class/power_supply/BAT0/$f 2>/dev/null || echo "not supported")"
   done'

section_sh "AC adapter" 'for p in /sys/class/power_supply/A[CD]*; do echo "$p online: $(cat $p/online 2>/dev/null)"; done'
section "Sensors / thermal" sensors
section_sh "Sleep states available" 'cat /sys/power/mem_sleep 2>/dev/null'

# --- devices ---------------------------------------------------------------

section_sh "PCI devices (key subsystems)" \
  'lspci -nnk | grep -A3 -iE "vga|3d|network|audio|non-volatile|thunderbolt"'
section_sh "Network interfaces" 'ip -brief addr'
section_sh "Loaded modules (key)" 'lsmod | grep -iE "iwlwifi|i915|xe|thunderbolt|nvme|snd_sof|dell" | sort'
section "Firmware update devices (fwupd)" fwupdmgr get-devices

# --- footer ----------------------------------------------------------------

cat >> "$OUTFILE" <<'EOF'

---

## Interpretation

Cross-reference this report against the project documentation:

| Section here | Document |
|---|---|
| CPU, memory, PCI, battery, sensors | [01 — Hardware Inventory](../docs/01-hardware-inventory.md) |
| Partition table, blkid, SMART, LBA formats | [02 — Storage Analysis](../docs/02-storage-analysis.md) |
| Secure Boot, EFI entries, TPM | [06 — BIOS/UEFI Configuration](../docs/06-bios-uefi-configuration.md) |
| CPU vulnerabilities, battery health, error log | [07 — Findings & Risks](../docs/07-findings-and-risks.md) |
| Target state and acceptance criteria | [08 — Reference Architecture](../docs/08-reference-architecture.md) |

### Quick red flags

- `gather_data_sampling: Vulnerable` → install `intel-microcode` (F-06)
- Battery `capacity` well below 80% → replace the cell (F-01)
- `Unsafe Shutdowns` climbing → power delivery problem (F-04)
- `Media and Data Integrity Errors` non-zero → **drive failing, back up now**
- `Percentage Used` above ~80% → drive approaching end of endurance
- `DISC-MAX` zero on the NVMe device → TRIM is not reaching the SSD
EOF

echo >&2
echo "Done: $OUTFILE" >&2
if [[ $REDACT -eq 0 ]]; then
  echo "WARNING: redaction was DISABLED. This file contains serial numbers." >&2
  echo "         Do NOT commit it to a public repository." >&2
fi
